version: '3.8'

services:
  vinylbuddy:
    image: potseeslc/vinylbuddy:latest
    ports:
      - "3000:3000"
    volumes:
      - vinyl-uploads:/app/uploads
    environment:
      - NODE_ENV=production

volumes:
  vinyl-uploads:
